import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/ui/globals.css";
import SessionWrapper from "@/app/ui/SessionWrapper";
import Header from "@/app/ui/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <Header />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
